// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © blockplus

//@version=5
indicator("PINE教学1：执行模型", overlay=true)

var count = 0
count += 1

txt = "第" + str.tostring(count) +"次执行PINE脚本\n" +
     "===== K线数据 =====：" +"\n" +
     "K线开盘价：" + str.tostring(open) +"\n" +
     "K线收盘价：" + str.tostring(close) +"\n" +
     "K线最高价：" + str.tostring(high) +"\n" + 
     "K线最低价：" + str.tostring(low) +"\n" +
     "K线成交量：" + str.tostring(volume) +"\n"+
     "===== 指标数据 =====：" +"\n" +
     "K线位置SMA12：" + str.tostring(ta.sma(close, 3)) +"\n" + 
     "K线位置EMA12：" + str.tostring(ta.ema(close, 3)) +"\n" +
     "K线位置RSI：" + str.tostring(ta.rsi(close, 3)) +"\n ..."

label1 = label.new(bar_index, low, text=txt, style=label.style_label_up, color=color.white)
label.set_x(label1, bar_index)
label.delete(label1[1])

